In [1]:
import numpy as np

In [2]:
print("Hello world")

Hello world


In [3]:
# 123123123123 test
# ctrl + /
# 마크다운 변환 m, 코드 변환 y

### test
## test
# test

# 조건문

In [4]:
a = 8

if (a<8): # 조건 만족
    print("작은 수")
else:
    print("큰 수")

큰 수


# 반복문

In [5]:
# for i in range(a,b): # 1:반복횟수 a:시작, b:끝
for x in range(0,10):
    for y in range(0,5):
        print(x,y)

0 0
0 1
0 2
0 3
0 4
1 0
1 1
1 2
1 3
1 4
2 0
2 1
2 2
2 3
2 4
3 0
3 1
3 2
3 3
3 4
4 0
4 1
4 2
4 3
4 4
5 0
5 1
5 2
5 3
5 4
6 0
6 1
6 2
6 3
6 4
7 0
7 1
7 2
7 3
7 4
8 0
8 1
8 2
8 3
8 4
9 0
9 1
9 2
9 3
9 4


In [6]:
b = np.array([1,3,5])
b1 = np.array([2,4,6])
c = np.array([[1],[3],[5]])
d = np.array([[1,2],[3,4]])

print(b*0+b1*1)
print(c)
print(d)

[2 4 6]
[[1]
 [3]
 [5]]
[[1 2]
 [3 4]]


In [7]:
x = np.zeros((2,3))
print(x)


y = np.ones((2,3))
print(y)

z = np.ones((2,3)) *100
print(z)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[100. 100. 100.]
 [100. 100. 100.]]


In [8]:
x = np.array([[1,2,3],[4,5,6]])
print(np.mean(x))

print(np.mean(x,axis=1))

# 슬라이싱
print(x[:,1])
print(x[0,1])
print(x[:,:])

3.5
[2. 5.]
[2 5]
2
[[1 2 3]
 [4 5 6]]


In [9]:
A = np.array([[1,2,3],[4,5,6]])
for x in range(0,2):
    for y in range(0,3):
        A[x,y] = A[x,y]*3
        print(A)

[[3 2 3]
 [4 5 6]]
[[3 6 3]
 [4 5 6]]
[[3 6 9]
 [4 5 6]]
[[ 3  6  9]
 [12  5  6]]
[[ 3  6  9]
 [12 15  6]]
[[ 3  6  9]
 [12 15 18]]


In [10]:
print(A**2)

[[  9  36  81]
 [144 225 324]]


# 9.15

In [11]:
x = np.array([[1,12],[2,22],[3,100]])
print(x)
print(x[2,1])
print(x[1,:])
print(x[:,0])

[[  1  12]
 [  2  22]
 [  3 100]]
100
[ 2 22]
[1 2 3]


In [14]:
x = np.array([[1,12],[2,22],[3,100]])
print(x)
print(x[2,1])
print(x[1,:])
print(x[:,0])

[[  1  12]
 [  2  22]
 [  3 100]]
100
[ 2 22]
[1 2 3]


In [12]:
import math
print(math.sqrt(9))
print(np.sqrt([1,2,3]))
print((x**2))

3.0
[1.         1.41421356 1.73205081]
[[    1   144]
 [    4   484]
 [    9 10000]]


In [13]:
import matplotlib.pyplot as plt
num1 = np.array([[0,0,1,0,0],
                [0,0,1,0,0],
                [0,0,1,0,0],
                [0,0,1,0,0],
                [1,1,1,1,1]])

num2 = np.array([[0,0,1,0,0],
                [0,0,1,0,0],
                [0,0,1,0,0],
                [0,0,1,0,0],
                [1,1,1,1,1]])

print(num1+num2)
# plt.imshow(num, cmap="gray")


[[0 0 2 0 0]
 [0 0 2 0 0]
 [0 0 2 0 0]
 [0 0 2 0 0]
 [2 2 2 2 2]]
